export const BASE_URL = "http://localhost:8080";
// export const BASE_URL = "http://3.92.30.172:8080";
export const States = ["Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana nebraska",
    "Nevada",
    "New hampshire",
    "New jersey",
    "New mexico",
    "New york",
    "North carolina",
    "North dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania rhode island",
    "South carolina",
    "South dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "washington",
    "west virginia",
    "Wisconsin",
    "Wyoming"];
export const GOOGLE_CLIENT_ID = "376399747753-hnqcdk72tcdmqcrrged6hfqdf9r3o4l2.apps.googleusercontent.com"
export const FACEBOOK_APP_ID = "528182401372238"
